/**
 * 「サイト設定」オンラインエディターのフィールド名の日本語訳。
 *
 * 設定ページは、各設定ファイル（site/profile/navbar/footer/sidebar）のフィールドを
 * 入力フォームとして表示しますが、フィールドのキー名自体は英語（themeColor、pageWidth など）です。
 * このファイルは「英語キー名 -> 日本語ラベル」の辞書を提供します。
 *
 * 注意：ここで翻訳しているのは*フィールド名*であり、設定値（url、title などのテキスト）は
 * ユーザーデータなので翻訳しません。
 */

export const JAPANESE_LABELS: Record<string, string> = {
	// —— サイト（SiteConfig）——
	title: "サイトタイトル",
	subtitle: "サブタイトル",
	site_url: "サイトURL",
	description: "サイトの説明",
	keywords: "キーワード",
	lang: "言語",
	themeColor: "テーマカラー",
	hue: "色相",
	fixed: "色相固定",
	defaultMode: "デフォルトモード",
	pageWidth: "ページ幅",
	card: "カードスタイル",
	border: "カードのボーダー",
	followTheme: "テーマカラーに追従",
	siteStartDate: "サイト開設日",
	timezone: "タイムゾーン",
	favicon: "サイトアイコン",
	src: "画像URL",
	sizes: "サイズ",
	theme: "テーマ",
	navbar: "ナビゲーションバー",
	logo: "ナビバーロゴ",
	type: "タイプ",
	value: "内容",
	alt: "画像の説明",
	widthFull: "幅いっぱいに表示",
	menuAlign: "メニューの配置",
	stickyNavbar: "ナビバー固定",
	mode: "モード",
	pages: "ページの表示切替",
	friends: "友链ページ",
	sponsor: "スポンサーページ",
	guestbook: "掲示板ページ",
	bangumi: "番組計画ページ",
	gallery: "アルバムページ",
	anime: "追番ページ",
	app: "アプリ推薦ページ",
	music: "音楽ページ",
	categoryBar: "カテゴリーナビゲーションバー",
	foldArticle: "過去の年アーカイブを折りたたむ",
	postListLayout: "記事一覧レイアウト",
	mobileDefaultMode: "モバイルのデフォルトモード",
	showTags: "タグを表示",
	descriptionLines: "説明の行数",
	allowSwitch: "レイアウトの切り替えを許可",
	grid: "グリッドレイアウト",
	masonry: "メイソンリーレイアウト",
	columnWidth: "カードの最小幅",
	post: "記事設定",
	rehypeCallouts: "注意枠",
	enablePythonMarkdownAdmonitions: "Python注意構文を有効化",
	showLastModified: "最終編集日時を表示",
	outdatedThreshold: "古さ判定(日数)",
	sharePoster: "共有ポスター",
	generateOgImages: "OG画像を生成",
	userId: "ユーザーID",
	apiUrl: "API URL",
	subjectBaseUrl: "詳細ページURL",
	categoryOrder: "タイプの並び順",
	bilibili: "Bilibili",
	uid: "UID",
	tmdb: "TMDB",
	apiKey: "APIキー",
	listId: "リストID",
	pagination: "ページング設定",
	postsPerPage: "1ページあたりの記事数",
	imageOptimization: "画像最適化",
	formats: "出力フォーマット",
	quality: "圧縮品質",
	noReferrerDomains: "ホットリンク防止ドメイン",

	// —— プロフィール（ProfileConfig）——
	avatar: "アバター",
	name: "名前",
	bio: "自己紹介",
	links: "リンク一覧",
	url: "リンクURL",
	icon: "アイコン",
	showName: "名前を表示",

	// —— フッター（FooterConfig）——
	enable: "有効",
	customHtml: "カスタムHTML",

	// —— サイドバー（SidebarLayoutConfig）——
	position: "サイドバーの位置",
	tabletSidebar: "タブレットのサイドバー",
	hideSidebarOnPostPage: "記事ページでサイドバーを非表示",
	showBothSidebarsOnPostPage: "記事ページで両方のサイドバーを表示",
	leftComponents: "左側コンポーネント",
	rightComponents: "右側コンポーネント",
	mobileBottomComponents: "モバイルの下部コンポーネント",
	showTitle: "タイトルを表示",
	showOnPostPage: "記事ページで表示",
	hideOnNonPostPage: "記事ページのみ表示",
	specificConfig: "専用設定",
	customProps: "カスタム属性",
	hidden: "非表示デバイス",
	collapseThreshold: "折りたたみの閾値",
	calendar: "カレンダー",
	showHeatmap: "年間ヒートマップ",
	ad: "広告設定",
	content: "内容",
	link: "リンクボタン",
	text: "ボタンの文字",
	external: "新しいウィンドウで開く",
	padding: "内側パディング",
	displayCount: "表示回数",
	closable: "閉じるボタンを表示",
	expireDate: "有効期限",
	image: "広告画像",
	header: "見出し",
	siteInfo: "サイト情報",
	unknownBuildPlatform: "不明機種の文言",

	// —— ナビゲーションバー（NavBarConfig）——
	children: "サブメニュー",
	pageKey: "ページ識別キー",
	method: "検索方式",
};