/**
 * Русские подписи полей для онлайн-редактора «Конфигурация сайта».
 *
 * Поля конфигурационных файлов (site/profile/navbar/footer/sidebar) имеют
 * английские ключи (например, themeColor, pageWidth). Этот словарь сопоставляет
 * английские ключи с краткими русскими подписями, которые отображаются в форме
 * конфигурации. Переводятся только имена полей, а не значения пользовательских данных.
 */

export const RUSSIAN_LABELS: Record<string, string> = {
	// —— Сайт (SiteConfig) ——
	title: "Заголовок сайта",
	subtitle: "Подзаголовок",
	site_url: "URL сайта",
	description: "Описание",
	keywords: "Ключевые слова",
	lang: "Язык",
	themeColor: "Цвет темы",
	hue: "Оттенок",
	fixed: "Фиксированный оттенок",
	defaultMode: "Режим по умолчанию",
	pageWidth: "Ширина страницы",
	card: "Стиль карточек",
	border: "Рамка карточек",
	followTheme: "Следовать цвету темы",
	siteStartDate: "Дата создания сайта",
	timezone: "Часовой пояс",
	favicon: "Иконка сайта",
	src: "URL изображения",
	sizes: "Размеры",
	theme: "Тема",
	navbar: "Навигационная панель",
	logo: "Логотип навигации",
	type: "Тип",
	value: "Содержимое",
	alt: "Описание изображения",
	widthFull: "На всю ширину",
	menuAlign: "Выравнивание меню",
	stickyNavbar: "Закреплённая навигация",
	mode: "Режим",
	pages: "Переключатели страниц",
	friends: "Страница друзей",
	sponsor: "Страница спонсоров",
	guestbook: "Страница гостевой книги",
	bangumi: "Страница аниме-плана",
	gallery: "Страница галереи",
	anime: "Страница аниме",
	app: "Страница приложений",
	music: "Страница музыки",
	categoryBar: "Панель категорий",
	foldArticle: "Сворачивать старые архивы",
	postListLayout: "Макет списка статей",
	mobileDefaultMode: "Мобильный режим по умолчанию",
	showTags: "Показывать теги",
	descriptionLines: "Строки описания",
	allowSwitch: "Разрешить смену макета",
	grid: "Сетка",
	masonry: "Плиточный макет",
	columnWidth: "Мин. ширина карточки",
	post: "Настройки статей",
	rehypeCallouts: "Примечания-выноски",
	enablePythonMarkdownAdmonitions: "Python-синтаксис примечаний",
	showLastModified: "Показывать дату изменения",
	outdatedThreshold: "Порог устаревания (дней)",
	sharePoster: "Постер для шаринга",
	generateOgImages: "Генерировать OG-изображения",
	userId: "ID пользователя",
	apiUrl: "URL API",
	subjectBaseUrl: "URL страницы предмета",
	categoryOrder: "Порядок категорий",
	bilibili: "Bilibili",
	uid: "UID",
	tmdb: "TMDB",
	apiKey: "Ключ API",
	listId: "ID списка",
	pagination: "Постраничная навигация",
	postsPerPage: "Статей на странице",
	imageOptimization: "Оптимизация изображений",
	formats: "Форматы вывода",
	quality: "Качество сжатия",
	noReferrerDomains: "Домены без referrer",

	// —— Профиль (ProfileConfig) ——
	avatar: "Аватар",
	name: "Имя",
	bio: "Подпись",
	links: "Список ссылок",
	url: "Адрес ссылки",
	icon: "Иконка",
	showName: "Показывать имя",

	// —— Подвал (FooterConfig) ——
	enable: "Включить",
	customHtml: "Пользовательский HTML",

	// —— Боковая панель (SidebarLayoutConfig) ——
	position: "Положение боковой панели",
	tabletSidebar: "Боковая панель на планшете",
	hideSidebarOnPostPage: "Скрывать панель на страницах статей",
	showBothSidebarsOnPostPage: "Показывать две панели на страницах статей",
	leftComponents: "Левые компоненты",
	rightComponents: "Правые компоненты",
	mobileBottomComponents: "Мобильные нижние компоненты",
	showTitle: "Показывать заголовок",
	showOnPostPage: "Показывать на страницах статей",
	hideOnNonPostPage: "Только на страницах статей",
	specificConfig: "Специальная конфигурация",
	customProps: "Пользовательские свойства",
	hidden: "Скрытые устройства",
	collapseThreshold: "Порог сворачивания",
	calendar: "Календарь",
	showHeatmap: "Годовая тепловая карта",
	ad: "Настройки рекламы",
	content: "Содержимое",
	link: "Кнопка-ссылка",
	text: "Текст кнопки",
	external: "Открывать в новой вкладке",
	padding: "Внутренний отступ",
	displayCount: "Количество показов",
	closable: "Можно закрыть",
	expireDate: "Срок действия",
	image: "Рекламное изображение",
	header: "Заголовок",
	siteInfo: "Информация о сайте",
	unknownBuildPlatform: "Текст неизвестной платформы",

	// —— Навигация (NavBarConfig) ——
	children: "Подменю",
	pageKey: "Идентификатор страницы",
	method: "Способ поиска",
};
